import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("register", "routes/register.tsx"),
  route("logout", "routes/logout.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("auth/github", "routes/auth.github.tsx"),
  route("auth/github/callback", "routes/auth.github.callback.tsx"),
  route("connect-github", "routes/connect-github.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("profile", "routes/profile.tsx"),
  route("projects", "routes/projects.tsx"),
  route("projects/:id", "routes/project-detail.tsx"),
  route("careers", "routes/careers.tsx"),
  route("careers/:id", "routes/career-detail.tsx"),
  route("career-apply-action", "routes/career-apply-action.tsx"),
  route("about", "routes/about.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("contact", "routes/contact.tsx"),
  route("updates", "routes/updates.tsx"),
  route("applications", "routes/applications.tsx"),
  route("apply-action", "routes/apply-action.tsx"),
  route("ideas-submit", "routes/ideas-submit.tsx"),
  route("dev/:username", "routes/dev-profile.tsx"),
  route("api/check-username", "routes/api.check-username.ts"),
  route("api/github-webhook", "routes/api.github-webhook.ts"),
  route("api/phone-send-otp", "routes/api.phone-send-otp.ts"),
  route("api/phone-verify-otp", "routes/api.phone-verify-otp.ts"),


  // SEO Infrastructure
  route("sitemap.xml", "routes/sitemap[.xml].tsx"),
  route("sitemap-images.xml", "routes/sitemap-images[.xml].tsx"),
  route("health.json", "routes/health[.json].tsx"),

  route("admin/verify", "routes/admin/verify.tsx"),
  route("admin/reset-pin", "routes/admin/reset-pin.tsx"),
  // Admin panel — protected by requireAdmin and requireAdminGate in layout or loaders
  layout("routes/admin/layout.tsx", [
    route("admin", "routes/admin/dashboard.tsx"),
    route("admin/approvals", "routes/admin/approvals.tsx"),
    route("admin/projects", "routes/admin/projects.tsx"),
    route("admin/applications", "routes/admin/applications.tsx"),
    route("admin/applications/:id", "routes/admin/application-detail.tsx"),
    route("admin/careers", "routes/admin/careers.tsx"),
    route("admin/career-applications", "routes/admin/career-applications.tsx"),
    route("admin/career-applications/:id", "routes/admin/career-application-detail.tsx"),
    route("admin/contacts", "routes/admin/contacts.tsx"),
    route("admin/updates", "routes/admin/updates.tsx"),
    route("admin/members", "routes/admin/members.tsx"),
    route("admin/teams", "routes/admin/teams.tsx"),
    route("admin/interviews", "routes/admin/interviews.tsx"),
    route("admin/progress", "routes/admin/progress.tsx"),
    route("admin/certificates", "routes/admin/certificates.tsx"),
    route("admin/showcase", "routes/admin/showcase.tsx"),
    route("admin/revenue", "routes/admin/revenue.tsx"),
    route("admin/comms", "routes/admin/comms.tsx"),
    route("admin/leaderboard", "routes/admin/leaderboard-admin.tsx"),
    route("admin/analytics", "routes/admin/analytics.tsx"),
    route("admin/audit", "routes/admin/audit.tsx"),
    route("admin/ideas", "routes/admin/ideas.tsx"),
    route("admin/settings", "routes/admin/settings.tsx"),
  ]),
] satisfies RouteConfig;